server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/epidemic?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: decadez
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 0 # 几号库
    lettuce:
      pool:
        max-active: 8 # 最大连接
        max-idle: 8 # 最大空闲连接
        min-idle: 0 # 最小空闲连接
        max-wait: 100ms # 连接等待时间}

  jpa:
    hibernate:
      ddl-auto: update
  sql:
    init:
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql
      mode: always

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

image:
  #  win 不同开发环境需要注意路径
  path: D:\DECADEZ\epidemic-master\server-static\images
  # mac
#  path: /Users/decadez/Desktop/my-project/epidemic-master/server-static/images
